# Generated by Django 5.1.7 on 2026-01-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('aseguradora_salud', models.CharField(choices=[('FONASA', 'FONASA'), ('ISAPRE_BANMEDICA', 'Isapre Banmédica'), ('ISAPRE_CONSALUD', 'Isapre Consalud'), ('ISAPRE_COLMENA', 'Isapre Colmena'), ('ISAPRE_CRUZ_BLANCA', 'Isapre Cruz Blanca'), ('ISAPRE_VIDA_TRES', 'Isapre Vida Tres'), ('OTRA', 'Otra')], max_length=50, verbose_name='Aseguradora de Salud')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
    ]
