# Generated by Django 5.1.7 on 2026-01-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VENDIDO', 'Vendido'), ('ARRENDADO', 'Arrendado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha Publicación')),
                ('destacada', models.BooleanField(default=False, verbose_name='Destacada')),
                ('tipo_propiedad', models.CharField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo Propiedad')),
                ('operacion', models.CharField(choices=[('VENTA', 'Venta'), ('ARRIENDO', 'Arriendo'), ('AMBOS', 'Venta y Arriendo')], max_length=15, verbose_name='Operación')),
                ('superficie_total_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sup. Total m²')),
                ('superficie_construida_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sup. Construida m²')),
                ('numero_piezas', models.PositiveIntegerField(verbose_name='Nº Piezas')),
                ('numero_banos', models.PositiveIntegerField(verbose_name='Nº Baños')),
                ('estacionamientos', models.PositiveIntegerField(default=0, verbose_name='Estacionamientos')),
                ('bodegas', models.PositiveIntegerField(default=0, verbose_name='Bodegas')),
                ('precio_venta_clp', models.BigIntegerField(default=0, verbose_name='Precio Venta CLP')),
                ('precio_venta_uf', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Venta UF')),
                ('precio_arriendo_clp', models.BigIntegerField(default=0, verbose_name='Precio Arriendo CLP')),
                ('precio_arriendo_uf', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Arriendo UF')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_publicacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=1024)),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es Principal')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedad',
                'ordering': ['orden', '-es_principal'],
            },
        ),
    ]
